---
  - set_fact: instance_id={{ hostvars[instance].instance_id }}

  - name: Getting instance ip
    shell: "aws ec2 describe-instances --instance-ids {{ instance_id }} --query 'Reservations[0].Instances[0].PublicIpAddress' "
    register: ec2_response

  - set_fact: instance_public_ip="{{ec2_response.stdout | from_json}}"

  - debug: msg="{{instance_public_ip}}"

  - name: Create Cloudflare DNS record
    cloudflare_dns:
      zone: "{{CLOUD_FLARE.ZONE}}"
      record: "{{PROJECT_NAME}}"
      type: A
      value: unique value
      solo: true
      proxied: true
      value: "{{instance_public_ip}}"
      account_email: "{{CLOUD_FLARE.ACCOUNT_EMAIL}}"
      account_api_token: "{{CLOUD_FLARE_API_TOKEN}}"
      state: present
    register: record

  - debug: msg="{{record}}"

  - name: Creating hosts file
    template: src="{{playbook_dir}}/templates/hosts.jinja2" dest="{{playbook_dir}}/../hosts"