--- # Playbook to start instance
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug: msg="{{ hostvars[item].instance_id }}"
      with_items:
        - "{{groups.all}}"

    - name: Starting instance
      shell: "aws ec2 start-instances --instance-ids {{ hostvars[item].instance_id }}"
      with_items:
        - "{{ groups.all }}"

    - name: Pausing for 5 mins to start instance
      wait_for: timeout=3

    - include: _start.yaml instance={{item}}
      with_items:
        - "{{ groups.all }}"
