--- # Playbook to stop instance
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug: msg="{{ hostvars[item].instance_id }}"
      with_items:
       - "{{groups.all}}"

    - name: Stopping instance
      shell: "aws ec2 stop-instances --instance-ids {{ hostvars[item].instance_id }}"
      with_items:
        - "{{ groups.all }}"