- hosts: cobbler
  tasks:
    - name: Disabling SELinux
      action: selinux policy=targeted state=permissive
    - name: Install epel repo
      shell: rpm -Uvh https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
      ignore_errors: True
    - name: Install cobbler
      yum: pkg={{ item }} state=installed
      with_items:
      - vim
      - ntp
      - dhcp
      - yum-utils
      - wget
      - cobbler
      - cobbler-web
      - pykickstart
      - syslinux
      - PyYAML
      - Django
    - name: Configure xinetd
      lineinfile: dest=/etc/xinetd.d/tftp regexp="disable.*= yes" line="disable                 = no"
    - name: Configuring cobbler
      lineinfile:
        dest: /etc/cobbler/settings
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        state: present
      with_items:
          - {regex: "next_server: 127.0.0.1", line: "next_server: 5.5.5.2"}
          - {regex: "server: 5.5.5.2", line: "next_server: 5.5.5.2"}
          - {regex: "manage_dhcp: 0", line: "manage_dhcp: 1"}
    - name: Copy DHCP template
      copy: src=./dhcp.template dest=/etc/cobbler/
    - name: Starting services
      service: name={{ item }} state=started enabled=yes
      with_items:
        - httpd
        - cobblerd
    - name: Get coobler loaders
      shell: cobbler get-loaders

    - name: Cobbler sync and restart
      shell: cobbler sync

