mongo_ip: 127.0.0.1
mongo_port: 27017
mongo_admin_user: pyromann
mongo_admin_pass: 1q2w3e4r
mongo_db_path: "/data/mongo/"
mongo_log_path: "/var/log/mongodb/mongod.log"
mongo_pid_path: "/var/run/mongodb/mongod.pid"
mongo_databases:
  - test

S3_BUCKET: "monogo.backup"
logs_dir: "/var/log/"