- name: "Install EPEL release"
  yum: name=epel-release

- name: "Install yum packages"
  yum: pkg={{item}}
  with_items:
    - git
    - docker-engine

- name: "Install python packages with pip"
  pip: name={{item.name}} version={{item.version}}
  with_items:
    - { name: docker-py, version: 1.10.6}

- name: "Enable docker service"
  service: name=docker state=started enabled=yes

- name: "Set aliases for docker"
  lineinfile: dest="/etc/bashrc" line={{item}}
  with_items: '{{docker_aliases}}'