--- # Creating services to handle redirects
- name: "Create http redirect service"
  template:
    src: "{{playbook_dir}}/templates/redirect-service.jinja2"
    dest: "/etc/systemd/system/redirect-{{item}}.service"
  with_items:
    - 80
    - 443
  become: yes

- name: "Reload systemctl"
  systemd:
    state: restarted
    daemon_reload: yes
  become: yes

- name: "Start redirect services"
  systemd:
    name: "redirect-{{item}}.service"
    state: started
    enabled: yes
    masked: no
  with_items:
    - 80
    - 443
  become: yes
