---
- name: "Run apt-get update"
  apt: update_cache=true
  become: yes

- name: "Installing ACL package"
  apt: pkg=acl
  become: yes

- name: "Installing packages"
  apt: name={{item}}
  with_items:
    - git
    - python-dev
    - python-pip
    - openssl
  become: yes

- name: "Clone devstack"
  git: repo=https://git.openstack.org/openstack-dev/devstack dest=/home/{{ansible_ssh_user}}/devstack

- name: "Create stack user"
  shell: "/home/{{ansible_ssh_user}}/devstack/tools/create-stack-user.sh"
  become: yes

- name: "Create config for devstack"
  template: src=local.conf.jinja2 dest=/home/{{ansible_ssh_user}}/devstack/local.conf


- name: "Run 'stack.sh'"
  shell: "/home/{{ansible_ssh_user}}/devstack/stack.sh"