---
- name: "Run apt-get update"
  apt: update_cache=true

- name: "Installing ACL package"
  apt: pkg=acl

- name: "Installing packages"
  apt: name={{item}}
  with_items:
    - git
    - python-dev
    - openssl

- name: "Clone devstack into /var/devstack"
  git: repo=https://git.openstack.org/openstack-dev/devstack dest=/opt/devstack

- name: "Create stack user"
  shell: "/opt/devstack/tools/create-stack-user.sh"

- name: "Create config for devstack"
  template: src=local.conf.jinja2 dest=/opt/devstack/local.conf

- name: "Chown devstack dir to user 'stack'"
  file: path=/opt/devstack/ owner=stack group=stack

- name: "Run 'stack.sh'"
  shell: "/opt/devstack/stack.sh"
  become_user: stack