- name: "Get nginx:alpine container"
  docker_image:
    name: nginx:alpine
    state: present

- name: "Start nginx container"
# Sinse there is a bug with ansble and docker, this is commented for now
#  docker_container:
#    name: nginx
#    state: started
#    published_ports:
#      - "80:80"
#      - "443:443"
  shell: "docker run -d -p 80:80 -p 443:443 --name=nginx nginx"